version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgres_bdii
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ifro_request
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_bdii
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ifro.edu.br
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"

  mongo:
    image: mongo:7
    container_name: mongo_bdii
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express_bdii
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8081:8081"
